# -----------------------
#   EVALUATION SETTINGS
# -----------------------

seed: 0
model: !include config/model/deepkernel/hsic/cnn3x64x256x512x256x128x64x32-bandwidth.yml
dataset: !include config/dataset/imagenet_c/imagenet_gn_zb_f.224x224.yml
dataloader:
  test: !torch.DataLoader
    shuffle: True
    drop_last: True
    num_workers: 6
    pin_memory: True

