# -----------------------
#   EVALUATION SETTINGS
# -----------------------

seed: 0
model: !include config/model/c2st/mlp/mlpB.dim50.yml

dataset:
  test: !dataset.HDGM
    name: HDGM-50
    size: 100000
    dim: 50

dataloader:
  test: !torch.DataLoader
    batch_size: 1000
    shuffle: True
    drop_last: True
    num_workers: 0
    pin_memory: True

