# -----------------------
#    DATASET SETTINGS
# -----------------------
name: RatInABox

train: !dataset.RatInABox &settings
  root: data/riab/raw/riab-20000-T.pkl
  split: train
  train_val_test_split: '4000:0:' #'4000:2000:16000'
  window: present
  transform: !transform.Compose
    - !transform.NumpyToTensor

val: !dataset.RatInABox
  <<: *settings
  split: val

test: !dataset.RatInABox
  <<: *settings
  split: test
