# -----------------------
#    DATASET SETTINGS
# -----------------------
name: RatInABox-n500

train: !dataset.RatInABox
  root: data/riab/raw/riab-10000-T.pkl
  size: 500
  split: train
  train_val_test_split: '2:1:1'
  window: present
  transform: !transform.Compose
    - !transform.NumpyToTensor

val: !dataset.RatInABox
  root: data/riab/raw/riab-10000-T.pkl
  size: 500
  split: val
  train_val_test_split: '2:1:1'
  window: present
  transform: !transform.Compose
    - !transform.NumpyToTensor

test: !dataset.RatInABox
  root: data/riab/raw/riab-10000-T.pkl
  size: 500
  split: test
  train_val_test_split: '2:1:1'
  window: present
  transform: !transform.Compose
    - !transform.NumpyToTensor
