# -----------------------
#    DATASET SETTINGS
# -----------------------
name: RatInABox-n5000

train: !dataset.RatInABox
  root: data/riab/raw/riab-10000.pkl
  size: 5000
  split: train
  train_val_test_split: '3:1:1'
  window: present
  transform: !transform.Compose
    - !transform.NumpyToTensor

val: !dataset.RatInABox
  root: data/riab/raw/riab-10000.pkl
  size: 5000
  split: val
  train_val_test_split: '3:1:1'
  window: present
  transform: !transform.Compose
    - !transform.NumpyToTensor

test: !dataset.RatInABox
  root: data/riab/raw/riab-10000.pkl
  size: 5000
  split: test
  train_val_test_split: '3:1:6'
  window: present
  transform: !transform.Compose
    - !transform.NumpyToTensor
