# -----------------------
#    DATASET SETTINGS
# -----------------------
name: RatInABox-n2000

train: !dataset.RatInABox
  root: data/riab/raw/riab-10000-T.pkl
  size: 2000
  split: train
  train_val_test_split: '1000:500:500'
  window: present
  transform: !transform.Compose
    - !transform.NumpyToTensor

val: !dataset.RatInABox
  root: data/riab/raw/riab-10000-T.pkl
  size: 2000
  split: val
  train_val_test_split: '1000:500:500'
  window: present
  transform: !transform.Compose
    - !transform.NumpyToTensor

test: !dataset.RatInABox
  root: data/riab/raw/riab-10000-T.pkl
  size: 2000
  split: test
  train_val_test_split: '1000:500:500'
  window: present
  transform: !transform.Compose
    - !transform.NumpyToTensor
