# -----------------------
#     MLP CLASSIFIER
# -----------------------

!model.Neck
name: id-id@mlpB.dim4
backbones: !nn.ModuleList
  - !model.Identity
  - !model.Identity
heads: !nn.ModuleList
  - !model.MLP
    name: mlpB
    features: [4, 8, 8, 4, 1]
    activations: ELU
    batch_norm: False
connection: cat
squeeze_single_head: True
