# -----------------------
#     MLP CLASSIFIER
# -----------------------

!model.Neck
name: id-id@mlpA.dim20
backbones: !nn.ModuleList
  - !model.Identity
  - !model.Identity
heads: !nn.ModuleList
  - !model.MLP
    name: mlpA
    features: [20, 60, 60, 60, 1]
    activations: ELU
    batch_norm: False
connection: cat
squeeze_single_head: True
