# -----------------------
#   EVALUATION SETTINGS
# -----------------------

seed: 0
model:
  tied: True
  k: !include config/model/deepkernel/mlp/mlpB.dim5.yml
  l: !include config/model/deepkernel/mlp/mlpB.dim5.yml

dataset:
  test: !dataset.HDGM
    name: HDGM-10
    size: 200000
    dim: 10

dataloader:
  test: !torch.DataLoader
    batch_size: 2000
    shuffle: True
    drop_last: True
    num_workers: 0
    pin_memory: True

