# -----------------------
#   EVALUATION SETTINGS
# -----------------------

seed: 0
model: !include config/model/c2st/mlp/mlpB.dim10.yml

dataset:
  test: !dataset.HDGM
    name: HDGM-10
    size: 10000
    dim: 10

dataloader:
  test: !torch.DataLoader
    batch_size: 100
    shuffle: True
    drop_last: True
    num_workers: 0
    pin_memory: True

