# -----------------------
#       ID-ID > MLP
# -----------------------

!kernel.DeepKernel
name: id-id@mlp10x32x64x32
featurizer: !model.Neck
  backbones: !nn.ModuleList
    - !model.Identity
    - !model.Identity
  heads: !nn.ModuleList
    - !model.FeedForward
      features: [10, 32, 64, 32]
      activation: relu
      batch_norm: False
      init: narrow_normal
  connection: cat
  squeeze_single_head: True
feature_kernel: !kernel.Gaussian
  scale: 1
  bandwidth: 1
  trainable: True
smoothing_kernel: !kernel.Gaussian
  scale: 1
  bandwidth: 1
  trainable: True
eps: 0.01
trainable: True
