# -----------------------
#        MLP-MLP
# -----------------------

name: mlp16x32x64x32-mlp2x4x8x4
tied: False

k: !kernel.DeepKernel
  featurizer: !model.FeedForward
    features: [16, 32, 64, 32]
    activation: ReLU
    batch_norm: False
    init: narrow_normal
  feature_kernel: !kernel.Gaussian
    scale: 1
    bandwidth: 1
    trainable: True
  smoothing_kernel: !kernel.Gaussian
    scale: 1
    bandwidth: 1
    trainable: True
  eps: 0.01
  trainable: True

l: !kernel.DeepKernel
  featurizer: !model.FeedForward
    features: [2, 4, 8, 4]
    activation: ReLU
    batch_norm: False
    init: narrow_normal
  feature_kernel: !kernel.Gaussian
    scale: 1
    bandwidth: 1
    trainable: True
  smoothing_kernel: !kernel.Gaussian
    scale: 1
    bandwidth: 1
    trainable: True
  eps: 0.01
  trainable: True
