# -----------------------
#        MLP-MLP
# -----------------------

name: mlp20x40x60x40-squared
tied: False
k: &deepkernel !kernel.DeepKernel
  featurizer: !model.FeedForward
    features: [20, 40, 60, 40]
    activation: relu
    batch_norm: False
    init: default
  feature_kernel: !kernel.Gaussian
    scale: 1
    bandwidth: 1
    trainable: True
  smoothing_kernel: !kernel.Gaussian
    scale: 1
    bandwidth: 1
    trainable: True
  eps: 0.01
  trainable: True
l: *deepkernel
