# -----------------------
#        MLP-MLP
# -----------------------

name: mlp5x10x15x10-tied
tied: True
k: &deepkernel !kernel.DeepKernel
  featurizer: !model.FeedForward
    features: [5, 10, 15, 10]
    activation: relu
    batch_norm: False
    init: kaiming
  feature_kernel: !kernel.Gaussian
    scale: 1
    bandwidth: 1
    trainable: True
  smoothing_kernel: !kernel.Gaussian
    scale: 1
    bandwidth: 1
    trainable: True
  eps: 0.01
  trainable: True
l: *deepkernel
