# -----------------------
#     Transformer
# -----------------------

name: transformer32#2_mlp12x128-transformer4#2_mlp12x128
tied: False

k: !kernel.DeepKernel
  featurizer: !nn.Sequential
    - !model.TransformerEncoder
      seq_len: 12
      embed_dim: 32
      num_heads: 4
      expansion_factor: 4
      num_layers: 2
      activation: GELU
      drop_attn: 0
      drop_ff: 0
    - !model.FeedForward
      features: [32, 1]
      activation: GELU
      last_nonlinear: True
    - !nn.Flatten -2
    - !model.FeedForward
      features: [12, 128]
      activation: GELU
      last_nonlinear: False
  feature_kernel: !kernel.Gaussian
    scale: 1
    bandwidth: 1
    trainable: True
  smoothing_kernel: !kernel.Gaussian
    scale: 1
    bandwidth: 1
    trainable: True
  eps: 0.01
  trainable: True

l: !kernel.DeepKernel
  featurizer: !nn.Sequential
    - !model.TransformerEncoder
      seq_len: 12
      embed_dim: 4
      num_heads: 4
      expansion_factor: 4
      num_layers: 2
      activation: GELU
      drop_attn: 0
      drop_ff: 0
    - !model.FeedForward
      features: [4, 1]
      activation: GELU
      last_nonlinear: True
    - !nn.Flatten -2
    - !model.FeedForward
      features: [12, 128]
      activation: GELU
      last_nonlinear: False
  feature_kernel: !kernel.Gaussian
    scale: 1
    bandwidth: 1
    trainable: True
  smoothing_kernel: !kernel.Gaussian
    scale: 1
    bandwidth: 1
    trainable: True
  eps: 0.01
  trainable: True

