# ------------------------
#    EVALUATION SETTINGS
# ------------------------
method: infonce
seed: 0

dataloader:
  test: !torch.DataLoader
    batch_size: 256
    shuffle: True
    drop_last: True
    num_workers: 0
    pin_memory: True

criterion: !criterion.MutualInfoLowerBound
  bound: info_nce
