# ------------------------
#    EVALUATION SETTINGS
# ------------------------
method: mi
seed: 0

dataloader:
  test: !torch.DataLoader
    batch_size: 32
    shuffle: True
    drop_last: True
    num_workers: 0
    pin_memory: True

criterion: !criterion.MITestPower
  normalize: False
