# -----------------------
#         CNN-0
# -----------------------

!model.CNN
channels:     [1,8,16,32,64,10]
kernel_size:  [4,4,4,4,1]
stride:       [2,2,2,1,1]
padding:      [1,1,1,0,0]
dilation:     [1,1,1,1,1]
activation:   LeakyReLU
batch_norm:   True

# 1x32x32   (Input)
# 2x16x16
# 4x8x8
# 8x4x4
# 16x1x1    (Output)
# 10x1x1

