# -----------------------
#      CNN-ID > MLP
# -----------------------

!model.Neck
name: cnn3x64x128x256x256x128-id@mlp129x1
backbones: !nn.ModuleList
  - !model.ConvNet
    channels:       [3,64,128,256,256,128]
    kernel_size:    [4,4,4,4,7]
    stride:         [2,2,2,2,1]
    padding:        [1,1,1,1,0]
    dilation:       [1,1,1,1,1]
    activation:     ELU
    batch_norm:     False
    last_nonlinear: False
    flatten:        True
  - !model.Identity
heads: !nn.ModuleList
  - !model.FeedForward
    features: [129, 1]
    activation: ReLU
    batch_norm: False
connection: cat
squeeze_single_head: True


# 3x112x112   (input)
# 64x56x56
# 128x28x28
# 256x14x14
# 256x7x7
# 128x1x1
# 129 > 1     (output)
