# -----------------------
#      CNN-ID > MLP
# -----------------------

!model.Neck
name: cnn3x8x16x32x32-id@mlp33x16x1
backbones: !nn.ModuleList
  - !model.ConvNet
    channels:       [3,8,16,32,32]
    kernel_size:    [4,4,4,4]
    stride:         [2,2,2,1]
    padding:        [1,1,1,0]
    dilation:       [1,1,1,1]
    activation:     ELU
    batch_norm:     False
    last_nonlinear: True
    flatten:        True
  - !model.Identity
heads: !nn.ModuleList
  - !model.FeedForward
    features: [33, 16, 1]
    activation: ELU
    batch_norm: False
connection: cat
squeeze_single_head: True

# ------------------
# 3x32x32   (input)
# 8x16x16
# 16x8x8
# 32x4x4
# 32x1x1
# ------------------
# 33 > 16 > 1   (output)
