# -----------------------
#     MLP CLASSIFIER
# -----------------------

!model.Neck
name: flatxid.cat.mlp
backbones: !nn.ModuleList
  - !model.Flatten
  - !model.Identity
heads: !nn.ModuleList
  - !model.MLP
    name: mlpA
    features: [3073, 1024, 256, 64, 1]
    activations: ELU
    batch_norm: False
connection: cat
squeeze_single_head: True
