# -----------------------
#       ID-ID > MLP
# -----------------------

!model.Neck
name: id-id@mlp4x8x12x8x1
backbones: !nn.ModuleList
  - !model.Identity
  - !model.Identity
heads: !nn.ModuleList
  - !model.FeedForward
    features: [4, 8, 12, 8, 1]
    activation: ReLU
    batch_norm: False
connection: cat
squeeze_single_head: True
