# -----------------------
#       ID-ID > MLP
# -----------------------

!model.Neck
name: id-id@mlp40x80x120x80x1
backbones: !nn.ModuleList
  - !model.Identity
  - !model.Identity
heads: !nn.ModuleList
  - !model.FeedForward
    features: [40, 80, 120, 80, 1]
    activation: ReLU
    batch_norm: False
connection: cat
squeeze_single_head: True
