# -----------------------
#    DATASET SETTINGS
# -----------------------
name: Alzheimer-800

train: !dataset.Alzheimer &settings
  root: data/alzheimer/raw/alzheimers_disease_data.csv
  split: train
  train_val_test_split: '480:0:'

val: !dataset.Alzheimer
  <<: *settings
  split: val

test: !dataset.Alzheimer
  <<: *settings
  split: test
