# -----------------------
#   EVALUATION SETTINGS
# -----------------------

seed: 0
model: !include config/model/deepkernel/mlp/mlpA.dim50.yml
dataset: !include config/dataset/hdgm/HDGM.dim50.yml
dataloader:
  test: !torch.DataLoader
    shuffle: True
    drop_last: True
    num_workers: 0
    pin_memory: True
