# -----------------------
#    TRAINING SETTINGS
# -----------------------

seed: 0
model: !include config/model/deepkernel/mlp/mlpB.dim4.yml
dataset: !include config/dataset/hdgm/HDGM.dim4.yml

dataloader:
  train: &loader !torch.DataLoader
    batch_size: 512
    shuffle: True
    drop_last: False
    num_workers: 0
    pin_memory: True
  val: *loader
  test: !torch.DataLoader
    batch_size: 2000  # each permutation test on 2000 samples
    shuffle: True
    drop_last: True
    num_workers: 0
    pin_memory: True

optimizer: !optim.AdamW
  lr: 1.0e-4
  betas: [0.9, 0.999]
  eps: 1.0e-8
  weight_decay: 0.005

criterion: !criterion.MMDTestPower
  reg: 1.e-8
