# -----------------------
#   EVALUATION SETTINGS
# -----------------------

seed: 0
model: !include config/model/infonce/id-id@mlp40x80x120x80x1.yml
dataset: !include config/dataset/hdgm/hdgm40.yml
dataloader:
  test: !torch.DataLoader
    shuffle: True
    drop_last: True
    num_workers: 0
    pin_memory: True
