# -----------------------
#     MLP CLASSIFIER
# -----------------------

!model.Neck
name: backbone:id_id;head:mlpB
backbones: !nn.ModuleList
  - !model.Identity
  - !model.Identity
heads: !nn.ModuleList
  - !model.MLP
    name: mlpB
    features: [50, 100, 100, 50, 1]
    activations: ELU
    batch_norm: False
connection: cat
squeeze_single_head: True
