# -----------------------
#   EVALUATION SETTINGS
# -----------------------

seed: 0
model: !kernel.Gaussian
  name: bandwidth
  scale: 1
  bandwidth: 1
  trainable: True
dataset:
  test: !dataset.HDGM
    name: HDGM-10
    size: 100000
    dim: 10
dataloader:
  test: !torch.DataLoader
    batch_size: 1000
    shuffle: True
    drop_last: True
    num_workers: 0
    pin_memory: True
