# -----------------------
#   EVALUATION SETTINGS
# -----------------------

seed: 0
model: !include config/model/deepkernel/hsic/transformer32#2_mlp12x64-transformer4#2_mlp12x64.yml
dataset: !include config/dataset/riab/riab_past.yml
dataloader:
  test: !torch.DataLoader
    shuffle: True
    drop_last: True
    num_workers: 0
    pin_memory: True

