# -----------------------
#   EVALUATION SETTINGS
# -----------------------

seed: 0
model: !kernel.Gaussian
  name: bandwidth
  scale: 1
  bandwidth: 1
  trainable: True
dataset:
  test: !dataset.HDGM
    name: HDGM-20
    size: 50000
    dim: 20
dataloader:
  test: !torch.DataLoader
    batch_size: 500
    shuffle: True
    drop_last: True
    num_workers: 0
    pin_memory: True
