# -----------------------
#   EVALUATION SETTINGS
# -----------------------

seed: 0
model:
  tied: False
  k: !include config/model/deepkernel/mlp/mlpB.dim15.yml
  l: !include config/model/deepkernel/mlp/mlpB.dim15.yml

dataset:
  test: !dataset.HDGM
    name: HDGM-30
    size: 10000
    dim: 30

dataloader:
  test: !torch.DataLoader
    batch_size: 100
    shuffle: True
    drop_last: True
    num_workers: 0
    pin_memory: True

