# -----------------------
#   EVALUATION SETTINGS
# -----------------------

seed: 0
model: !include config/model/infonce/transformer16#2-transformer2#2@24x64x1.yml
dataset: !include config/dataset/riab/riab_past.yml
dataloader:
  test: !torch.DataLoader
    shuffle: True
    drop_last: True
    num_workers: 0
    pin_memory: True

