# -----------------------
#    DATASET SETTINGS
# -----------------------
name: Blob-10

train: !dataset.Blob2ST
  size: 10000
  dim: 10

val: &data !dataset.Blob2ST
  size: 4000
  dim: 10

test: !dataset.Blob2ST
  size: 400000
  dim: 10

