# -----------------------
#   EVALUATION SETTINGS
# -----------------------

seed: 0
dataset:
  test: !dataset.HDGM
    size: 400000
    dim: 10
dataloader:
  test: !torch.DataLoader
    batch_size: 4000
    shuffle: True
    drop_last: True
    num_workers: 0
    pin_memory: True
