# -----------------------
#   EVALUATION SETTINGS
# -----------------------

seed: 0
model: !include config/model/deepkernel/mmd/cnn3x8x16x32x64-id@mlp65x32.yml
dataset: !include config/dataset/cifar10h/cifar10h.32x32.yml
dataloader:
  test: !torch.DataLoader
    shuffle: True
    drop_last: True
    num_workers: 0
    pin_memory: True

