# -----------------------
#   EVALUATION SETTINGS
# -----------------------

seed: 0
model:
  tied: False
  k: !include config/model/deepkernel/mlp/mlpA.dim20.yml
  l: !include config/model/deepkernel/mlp/mlpA.dim20.yml

dataset:
  test: !dataset.HDGM
    name: HDGM-40
    size: 100000
    dim: 40

dataloader:
  test: !torch.DataLoader
    batch_size: 1000
    shuffle: True
    drop_last: True
    num_workers: 0
    pin_memory: True

