# -----------------------
#    TRAINING SETTINGS
# -----------------------
method: mi
seed: 0

dataloader:
  train: !torch.DataLoader &loader
    batch_size: 64
    shuffle: True
    drop_last: False
    num_workers: 0
    pin_memory: True
  val: !torch.DataLoader
    <<: *loader
  test: !torch.DataLoader
    <<: *loader
    drop_last: True

optimizer: !optim.AdamW
  lr: 1.0e-4
  betas: [0.9, 0.999]
  eps: 1.0e-8
  weight_decay: 0.0001

criterion: !criterion.MITestPower
  normalize: True
