# -----------------------
#       ResNet50
# -----------------------

!kernel.DeepKernel
name: ResNet18x32
featurizer: !model.ResNet
  inter_channels: [64, 128, 256, 512]
  n_blocks: [3, 4, 6, 3]
  in_channels: 3
  out_features: 32
  activation: ReLU
  block_type: bottleneck
feature_kernel: !kernel.Gaussian
  scale: 1
  bandwidth: 1
  trainable: True
smoothing_kernel: !kernel.Gaussian
  scale: 1
  bandwidth: 1
  trainable: True
eps: 0.01
trainable: True
