# -----------------------
#    DATASET SETTINGS
# -----------------------
name: Telco-3000

train: !dataset.Telco &settings
  root: data/telco/raw/churn.csv
  split: train
  train_val_test_split: '1800:0:'

val: !dataset.Telco
  <<: *settings
  split: val

test: !dataset.Telco
  <<: *settings
  split: test
