# -----------------------
#      CNN-ID > MLP
# -----------------------

!model.Neck
name: cnn3x64x128x256x128x16-id@mlp17x16x1
backbones: !nn.ModuleList
  - !model.ConvNet
    channels:       [3,64,128,256,128,16]
    kernel_size:    [4,4,4,4,7]
    stride:         [2,2,2,2,1]
    padding:        [1,1,1,1,0]
    dilation:       [1,1,1,1,1]
    activation:     ReLU
    batch_norm:     False
    last_nonlinear: True
    flatten:        True
  - !model.Identity
heads: !nn.ModuleList
  - !model.FeedForward
    features: [17, 16, 1]
    activation: ReLU
    batch_norm: False
connection: cat
squeeze_single_head: True
squeeze_scalar_output: True


# 3x112x112   (input)
# 64x56x56
# 128x28x28
# 256x14x14
# 128x7x7
# 16x1x1
# 17 > 16 > 1     (output)
