# -----------------------
#     ResNET-ID > MLP
# -----------------------

!model.Neck
name: resnet18x32-id@mlp33x16x1
backbones: !nn.ModuleList
  - !model.ResNet
    inter_channels: [64, 128, 256, 512]
    n_blocks: [2, 2, 2, 2]
    in_channels: 3
    out_features: 32
    activation: ELU
    block_type: basic
  - !model.Identity
heads: !nn.ModuleList
  - !model.FeedForward
    features: [33, 16, 1]
    activation: ELU
    batch_norm: False
connection: cat
squeeze_single_head: True
squeeze_scalar_output: True
