# -----------------------
#   EVALUATION SETTINGS
# -----------------------

seed: 0
model:
  tied: False
  k: !include config/model/deepkernel/mlp/mlpA.dim2.yml
  l: !include config/model/deepkernel/mlp/mlpA.dim2.yml

dataset:
  test: !dataset.HDGM
    name: HDGM-4
    size: 20000
    dim: 4

dataloader:
  test: !torch.DataLoader
    batch_size: 200
    shuffle: True
    drop_last: True
    num_workers: 0
    pin_memory: True

