# ------------------------
#    EVALUATION SETTINGS
# ------------------------
method: nwj
seed: 0

dataloader:
  test: !torch.DataLoader
    batch_size: 64
    shuffle: True
    drop_last: True
    num_workers: 0
    pin_memory: True

criterion: !criterion.MutualInfoLowerBound
  bound: nwj
