# -----------------------
#      CNN-Gaussian
# -----------------------

name: cnn3x8x16x32x32x16x8-bandwidth
tied: False
k: !kernel.DeepKernel
  featurizer: !model.CNN
    channels:     [3,8,16,32,32,16,8]
    kernel_size:  [4,4,4,4,1,1]
    stride:       [2,2,2,1,1,1]
    padding:      [1,1,1,0,0,0]
    dilation:     [1,1,1,1,1,1]
    activation:   ELU
    batch_norm:   False
    flatten:      True
  feature_kernel: !kernel.Gaussian
    scale: 1
    bandwidth: 1
    trainable: True
  smoothing_kernel: !kernel.Gaussian
    scale: 1
    bandwidth: 50
    trainable: True
  eps: 0.01
  trainable: True
l: !kernel.Gaussian
  scale: 1
  bandwidth: 1
  trainable: True

# 3x32x32   (Input)
# 8x16x16
# 16x8x8
# 32x4x4
# 32x1x1
# 16x1x1
# 8x1x1     (Output)
