# -----------------------
#      CNN-Gaussian
# -----------------------

name: cnn3x64x256x512x256x128x64-bandwidth
tied: False
k: !kernel.DeepKernel
  featurizer: !model.CNN
    channels:     [3,64,256,512,256,128,64]
    kernel_size:  [4,4,4,4,4,7]
    stride:       [2,2,2,2,2,1]
    padding:      [1,1,1,1,1,0]
    dilation:     [1,1,1,1,1,1]
    activation:   ELU
    batch_norm:   False
    flatten:      True
  feature_kernel: !kernel.Gaussian
    scale: 1
    bandwidth: 1
    trainable: True
  smoothing_kernel: !kernel.Gaussian
    scale: 1
    bandwidth: 400
    trainable: True
  eps: 0.01
  trainable: True
l: !kernel.Gaussian
  scale: 1
  bandwidth: 1
  trainable: True

# 3x224x224   (Input)
# 64x112x112
# 256x56x56
# 512x28x28
# 256x14x14
# 128x7x7
# 64x1x1
