# -----------------------
#        MLP-MLP
# -----------------------

name: mlp10x20x30x20-tied
tied: True
k: &deepkernel !kernel.DeepKernel
  featurizer: !model.FeedForward
    features: [10, 20, 30, 20]
    activation: ELU
    batch_norm: False
  feature_kernel: !kernel.Gaussian
    scale: 1
    bandwidth: 1
    trainable: True
  smoothing_kernel: !kernel.Gaussian
    scale: 1
    bandwidth: 1
    trainable: True
  eps: 0.01
  trainable: True
l: *deepkernel
