# -----------------------
#        MLP-MLP
# -----------------------

name: mlp15x30x45x30-squared
tied: False
k: &deepkernel !kernel.DeepKernel
  featurizer: !model.MLP
    features: [15, 30, 45, 30]
    activations: ELU
    batch_norm: False
  feature_kernel: !kernel.Gaussian
    scale: 1
    bandwidth: 1
    trainable: True
  smoothing_kernel: !kernel.Gaussian
    scale: 1
    bandwidth: 1
    trainable: True
  eps: 0.01
  trainable: True
l: *deepkernel
