# -----------------------
#      MLP KERNEL
# -----------------------

!kernel.DeepKernel
name: mlpA
featurizer: !model.MLP
  features: [5, 15, 15, 15]
  activations: ELU
  batch_norm: False
feature_kernel: !kernel.Gaussian
  scale: 1
  bandwidth: 1
  trainable: True
smoothing_kernel: !kernel.Gaussian
  scale: 1
  bandwidth: 1
  trainable: True
eps: 0.01
trainable: True
