# -----------------------
#   EVALUATION SETTINGS
# -----------------------

seed: 0
model: !include config/model/bandwidth/hsic/bandwidth-squared.yml
dataset: !include config/dataset/imagenet_c/imagenet_gn_zb_f.224x224.yml
dataloader:
  test: !torch.DataLoader
    shuffle: True
    drop_last: True
    num_workers: 0
    pin_memory: True

