# -----------------------
#   Bandwidth-Bandwidth
# -----------------------

name: bandwidth-squared
tied: False
k: &kernel !kernel.Gaussian
  scale: 1
  bandwidth: 400
  flatten_input: True
  trainable: True
l: *kernel
