# -----------------------
#   EVALUATION SETTINGS
# -----------------------

seed: 0
model:
  tied: False
  k: !include config/model/deepkernel/mlp/mlpA.dim4.yml
  l: !include config/model/deepkernel/mlp/mlpA.dim4.yml

dataset:
  test: !dataset.HDGM
    name: HDGM-8
    size: 50000
    dim: 8

dataloader:
  test: !torch.DataLoader
    batch_size: 500
    shuffle: True
    drop_last: True
    num_workers: 0
    pin_memory: True

