# -----------------------
#    TRAINING SETTINGS
# -----------------------

seed: 0
model: !include config/model/c2st/resnet50x32-id@mlp33x16x1.yml
dataset: !include config/dataset/imagenet_c/imagenet_gn.224x224.yml

dataloader:
  train: &loader !torch.DataLoader
    batch_size: 256
    shuffle: True
    drop_last: False
    num_workers: 0
    pin_memory: True
  val: *loader
  test: !torch.DataLoader
    batch_size: 256
    shuffle: True
    drop_last: True
    num_workers: 0
    pin_memory: True

optimizer: !optim.AdamW
  lr: 1.0e-4
  betas: [0.9, 0.999]
  eps: 1.0e-8
  weight_decay: 0.0001

criterion: !criterion.BCEWithLogitsLoss
  reduction: mean
