# -----------------------
#    TRAINING SETTINGS
# -----------------------

seed: 0
model: !include config/model/c2st/flat-id@mlp/flat-id@mlpA.yml
dataset: !include config/dataset/cifar10h/cifar10h.32x32.yml

dataloader:
  train: &loader !torch.DataLoader
    batch_size: 512
    shuffle: True
    drop_last: False
    num_workers: 0    # Multiprocessing encounters errors on Windows
    pin_memory: True  # If you load your samples in the Dataset on CPU and would like to push it during training to the GPU, you can speed up the host to device transfer by enabling pin_memory
  val: *loader
  test: !torch.DataLoader
    batch_size: 128
    shuffle: True
    drop_last: True
    num_workers: 0
    pin_memory: True

optimizer: !optim.AdamW
  lr: 1.0e-4
  betas: [0.9, 0.999]
  eps: 1.0e-8
  weight_decay: 0.005

criterion: !criterion.BCEWithLogitsLoss
  reduction: mean
