# -----------------------
#   EVALUATION SETTINGS
# -----------------------

seed: 0
model:
  tied: True
  k: !include config/model/deepkernel/mlp/mlpA.dim25.yml
  l: !include config/model/deepkernel/mlp/mlpA.dim25.yml

dataset:
  test: !dataset.HDGM
    name: HDGM-50
    size: 400000  # 4000 samples * 100 batches
    dim: 50

dataloader:
  test: !torch.DataLoader
    batch_size: 4000
    shuffle: True
    drop_last: True
    num_workers: 0
    pin_memory: True

