# -----------------------
#    DATASET SETTINGS
# -----------------------
name: HDGM-50

train: !dataset.HDGM &settings
  size: 1000000
  dim: 50
  split: train
  train_val_test_split: '100000:4000:'

val: !dataset.HDGM
  <<: *settings
  split: val

test: !dataset.HDGM
  <<: *settings
  split: test
