# -----------------------
#    DATASET SETTINGS
# -----------------------

train: !dataset.HDGM
  name: HDGM-8
  size: 10000
  dim: 8

val: &data !dataset.HDGM
  name: HDGM-8
  size: 4000
  dim: 8

test: !dataset.HDGM
  name: HDGM-8
  size: 400000
  dim: 8

