# -----------------------
#    DATASET SETTINGS
# -----------------------
name: HDGM-30-n8000

train: !dataset.HDGM &settings
  size: 1000000
  dim: 30
  split: train
  train_val_test_split: '6000:0:'

val: !dataset.HDGM
  <<: *settings
  split: val

test: !dataset.HDGM
  <<: *settings
  split: test
