# -----------------------
#    DATASET SETTINGS
# -----------------------
name: HDGM-40

train: !dataset.HDGM &settings
  size: 1000000
  dim: 40
  split: train
  train_val_test_split: '100000:0:'

val: !dataset.HDGM
  <<: *settings
  split: val

test: !dataset.HDGM
  <<: *settings
  split: test
