# -----------------------
#    DATASET SETTINGS
# -----------------------
name: HDGM-10-n8000

train: !dataset.HDGM &data
  size: 8000
  dim: 10
  split: train
  train_val_test_split: '7:1:2'

val: !dataset.HDGM
  <<: *data
  split: val

test: !dataset.HDGM
  # <<: *data
  # split: test
  size: 10000   # 1600
  dim: 10
