# -----------------------
#    DATASET SETTINGS
# -----------------------
name: HDGM-20-n12000

train: !dataset.HDGM &data
  size: 12000
  dim: 20
  split: train
  train_val_test_split: '7:1:2'

val: !dataset.HDGM
  <<: *data
  split: val

test: !dataset.HDGM
  # <<: *data
  # split: test
  size: 10000   # 2400
  dim: 20
