# -----------------------
#    DATASET SETTINGS
# -----------------------
name: HDGM-30-n20000

train: !dataset.HDGM &settings
  size: 1000000
  dim: 30
  split: train
  train_val_test_split: '18000:0:'   # 9:0:1 # 7:0:3

val: !dataset.HDGM
  <<: *settings
  split: val

test: !dataset.HDGM
  <<: *settings
  split: test
