# -----------------------
#    DATASET SETTINGS
# -----------------------

train: !dataset.HDGM
  name: HDGM-20
  size: 100000  # *sometimes* works with 10,000 samples
  dim: 20

val: &data !dataset.HDGM
  name: HDGM-20
  size: 4000
  dim: 20

test: !dataset.HDGM
  name: HDGM-20
  size: 400000
  dim: 20

