# -----------------------
#    DATASET SETTINGS
# -----------------------
name: HDGM-30

train: !dataset.HDGM
  size: 100000  # needs at least 100,000 samples for deep kernel to train
  dim: 30

val: &data !dataset.HDGM
  size: 4000
  dim: 30

test: !dataset.HDGM
  size: 400000
  dim: 30
