# -----------------------
#    DATASET SETTINGS
# -----------------------
name: HDGM-8

train: !dataset.HDGM
  size: 10000
  dim: 8

val: &data !dataset.HDGM
  size: 4000
  dim: 8

test: !dataset.HDGM
  size: 10000
  dim: 8

