# -----------------------
#    DATASET SETTINGS
# -----------------------
name: HDGM-4

train: !dataset.HDGM
  size: 10000
  dim: 4

val: &data !dataset.HDGM
  size: 4000
  dim: 4

test: !dataset.HDGM
  size: 10000
  dim: 4

