# -----------------------
#    DATASET SETTINGS
# -----------------------
name: HDGM-20-n16000

train: !dataset.HDGM &settings
  size: 1000000
  dim: 20
  split: train
  train_val_test_split: '14400:0:'   # 9:0:1

val: !dataset.HDGM
  <<: *settings
  split: val

test: !dataset.HDGM
  <<: *settings
  split: test
