# -----------------------
#    DATASET SETTINGS
# -----------------------
name: HDGM-10-n4000

train: !dataset.HDGM &settings
  size: 1000000
  dim: 10
  split: train
  train_val_test_split: '3000:0:'

val: !dataset.HDGM
  <<: *settings
  split: val

test: !dataset.HDGM
  <<: *settings
  split: test
