# -----------------------
#    DATASET SETTINGS
# -----------------------

train: !dataset.HDGM
  name: HDGM-30
  size: 100000  # needs at least 100,000 samples for deep kernel to train
  dim: 30

val: &data !dataset.HDGM
  name: HDGM-30
  size: 4000
  dim: 30

test: !dataset.HDGM
  name: HDGM-30
  size: 200000  # 2000 samples * 100 batches
  dim: 30
