# -----------------------
#   EVALUATION SETTINGS
# -----------------------

seed: 0

model: !kernel.WeightedGaussian
  ndim: 10
  scale: 1
  bandwidth: 1
  trainable: True

dataset:
  test: !dataset.BlobHD
    size: 1000000
    dim: 20
    var: 1
    seed: 0

dataloader:
  test: !torch.DataLoader
    batch_size: 10000
    shuffle: True
    drop_last: True
    num_workers: 0
    pin_memory: True

