# -----------------------
#    TRAINING SETTINGS
# -----------------------

seed: 0
# model:
#   name: resnet50A-bandwidth
#   tied: False
#   k: !include config/model/deepkernel/cnn/cnnB.yml
#   l: !kernel.Gaussian
#     scale: 1
#     bandwidth: 1
#     trainable: True
dataset: !include config/dataset/imagenet-c/imagenet-c.224x224.yml

dataloader:
  train: &loader !torch.DataLoader
    batch_size: 512
    shuffle: True
    drop_last: False
    num_workers: 0
    pin_memory: True
  val: *loader
  test: !torch.DataLoader
    batch_size: 128
    shuffle: True
    drop_last: True
    num_workers: 0
    pin_memory: True

optimizer: !optim.AdamW
  lr: 1.0e-4
  betas: [0.9, 0.999]
  eps: 1.0e-8
  weight_decay: 0.005

criterion: !criterion.HSICTestPower
  reg: 1.e-8
