# -----------------------
#    TRAINING SETTINGS
# -----------------------

seed: 0
model: !include config/model/infonce/cnn3x8x16x32x64-id@mlp65x32x16x1.yml
dataset: !include config/dataset/cifar10h/cifar10h.32x32.yml

dataloader:
  train: &loader !torch.DataLoader
    batch_size: 512
    shuffle: True
    drop_last: False
    num_workers: 0
    pin_memory: True
  val: *loader
  test: !torch.DataLoader
    batch_size: 128
    shuffle: True
    drop_last: True
    num_workers: 0
    pin_memory: True

optimizer: !optim.AdamW
  lr: 1.0e-4
  betas: [0.9, 0.999]
  eps: 1.0e-8
  weight_decay: 0.0001

criterion: !criterion.MutualInfoLowerBound
  bound: info_nce
