# -----------------------
#   EVALUATION SETTINGS
# -----------------------

seed: 0
dataset: !include config/dataset/hdgm/HDGM.dim20.yml
dataloader:
  test: !torch.DataLoader
    shuffle: True
    drop_last: True
    num_workers: 0
    pin_memory: True
